import { describe,it,expect } from 'vitest';
import { BacktestInputSchema, type BacktestInput, type Strategy, type StrategyContext } from '../src/contracts';
import { simulate,compareStrategies } from '../src/engine';
import { naiveStrategy,robustStrategy,replenishment } from '../src/strategies';
import { csvCell,exportCsv } from '../src/csv';
import { createDemo } from '../data/demo/generate';
import { fromStockPilot } from '../src/adapter';
function fixture():BacktestInput { const d=createDemo()[0]!; return {sku:d.sku,observations:d.observations,startIndex:20,endIndex:51,settings:{initialStock:45,leadTimeDays:21,reviewPeriod:1,moq:5,packSize:5,serviceLevel:'0.95'},unitCost:850,currency:'₸',source:'sales'}; }
describe('Честная недельная симуляция',()=>{
  it('не передаёт текущие и будущие наблюдения',()=>{const input=fixture();let calls=0;simulate(input,c=>{expect(c.history).toEqual(input.observations.slice(0,input.startIndex+calls));expect(Object.keys(c).sort()).toEqual(['currentStock','history','openOrders','settings']);calls++;return naiveStrategy(c);},'spy');expect(calls).toBe(32);});
  it('будущий спрос не изменяет прошлые решения для обеих стратегий',()=>{const input=fixture(),changed=structuredClone(input);changed.observations[35]!.demand=99999;for(const strategy of [naiveStrategy,robustStrategy]){const a=simulate(input,strategy,'x'),b=simulate(changed,strategy,'x');expect(a.steps.slice(0,15)).toEqual(b.steps.slice(0,15));expect(a.steps[15]!.decision).toEqual(b.steps[15]!.decision);expect(a.steps[15]!.ordered).toEqual(b.steps[15]!.ordered);}});
  it('одинаковые начальные условия',()=>{const contexts:StrategyContext[]=[];const spy:Strategy=c=>{if(!contexts.length||contexts.length===1)contexts.push(structuredClone(c));return naiveStrategy(c);};const input=fixture();input.endIndex=input.startIndex;simulate(input,spy,'a');simulate(input,spy,'b');expect(contexts[0]).toEqual(contexts[1]);expect(contexts[0]!.currentStock).toBe(45);});
  it('поставка приходит ровно через ceil(days/7) недель',()=>{const input=fixture();input.settings.initialStock=0;input.settings.leadTimeDays=15;const r=simulate(input,naiveStrategy,'a');expect(r.leadTimeWeeks).toBe(3);expect(r.steps[0]!.ordered).toBeGreaterThan(0);expect(r.steps[0]!.receipts).toBe(0);expect(r.steps[1]!.receipts).toBe(0);expect(r.steps[2]!.receipts).toBe(0);expect(r.steps[3]!.receipts).toBe(r.steps[0]!.ordered);});
  it('нулевой срок: приход нового заказа до текущего спроса',()=>{const input=fixture();input.settings.initialStock=0;input.settings.leadTimeDays=0;const s=simulate(input,naiveStrategy,'a').steps[0]!;expect(s.receipts).toBe(s.ordered);expect(s.served).toBe(s.demand);});
  it('товар в пути закрывает потребность',()=>{const c:StrategyContext={history:[],currentStock:0,openOrders:[{placedAt:0,arrivesAt:3,quantity:40}],settings:fixture().settings};const d={forecast:10,deviation:0,adjustedCount:0,method:'fixed'};expect(replenishment(c,d)).toBe(0);expect(replenishment({...c,openOrders:[]},d)).toBe(40);});
  it('MOQ и упаковка округляются вверх, достаточный запас даёт ноль',()=>{const c:StrategyContext={history:[],currentStock:0,openOrders:[],settings:{...fixture().settings,moq:12,packSize:5}};const d={forecast:1,deviation:0,adjustedCount:0,method:'fixed'};expect(replenishment(c,d)).toBe(15);expect(replenishment({...c,currentStock:100},d)).toBe(0);});
  it('неотрицательность, баланс товара и спроса во всех демо и стратегиях',()=>{for(const demo of createDemo())for(const r of compareStrategies({...fixture(),sku:demo.sku,observations:demo.observations,startIndex:Math.min(2,demo.observations.length-1),endIndex:demo.observations.length-1})){for(const s of r.steps){expect(s.endingStock).toBeGreaterThanOrEqual(0);expect(s.ordered).toBeGreaterThanOrEqual(0);expect(s.openingStock+s.receipts-s.served).toBeCloseTo(s.endingStock);expect(s.served+s.unmet).toBeCloseTo(s.demand);if(s.ordered){expect(s.ordered%5).toBe(0);expect(s.ordered).toBeGreaterThanOrEqual(5);}}expect(45+r.steps.reduce((a,s)=>a+s.receipts-s.served,0)).toBeCloseTo(r.metrics.endingStock);}});
  it('нулевой спрос и пустая/короткая история безопасны',()=>{const input=fixture();input.observations=input.observations.map(o=>({...o,demand:0}));input.startIndex=0;input.settings.initialStock=0;for(const r of compareStrategies(input)){expect(r.metrics.orderedQuantity).toBe(0);expect(r.metrics.fillRate).toBe(1);}const c:StrategyContext={history:[],currentStock:0,openOrders:[],settings:input.settings};expect(robustStrategy(c).forecast).toBe(0);c.history=input.observations.slice(0,2).map(o=>({...o,demand:10}));expect(robustStrategy(c).forecast).toBe(10);});
  it('одиночный всплеск не раздувает устойчивый прогноз и не меняет исходники',()=>{const input=fixture();const c:StrategyContext={history:input.observations.slice(0,27),currentStock:0,openOrders:[],settings:input.settings};const before=structuredClone(c);expect(robustStrategy(c).forecast).toBeLessThan(13);expect(naiveStrategy(c).forecast).toBeGreaterThan(15);expect(c).toEqual(before);});
  it('повторный запуск идентичен',()=>expect(compareStrategies(fixture())).toEqual(compareStrategies(fixture())));
  it('не выдумывает стоимость при отсутствии себестоимости',()=>{const input=fixture();delete input.unitCost;for(const r of compareStrategies(input)){expect(r.metrics.purchaseCost).toBeUndefined();expect(r.metrics.averageInventoryCost).toBeUndefined();}expect(exportCsv(compareStrategies(input))).not.toContain('850');});
  it('CSV защищён от formula injection и экранирует кавычки',()=>{for(const s of ['=SUM(A1)','+cmd','-1+2','@test','  =1','\t=1','\rhello'])expect(csvCell(s).startsWith('"\'')).toBe(true);expect(csvCell('a"b')).toBe('"a""b"');const input=fixture();input.sku='=EVIL';input.observations=input.observations.map(o=>({...o,sku:input.sku}));expect(exportCsv(compareStrategies(input))).toContain('"\'=EVIL"');});
  it('отклоняет дубли, пропуски, неверный период и отрицательные значения',()=>{for(const mutate of [(x:BacktestInput)=>{x.startIndex=52;},(x:BacktestInput)=>{x.observations[1]!.date=x.observations[0]!.date;},(x:BacktestInput)=>{x.settings.packSize=0;},(x:BacktestInput)=>{x.observations[0]!.demand=-1;}]){const input=fixture();mutate(input);expect(BacktestInputSchema.safeParse(input).success).toBe(false);}});
  it('метрики считаются из событий, в пути не теряется',()=>{const r=compareStrategies(fixture())[0];expect(r.metrics.purchaseCost).toBe(r.metrics.orderedQuantity*850);expect(r.metrics.inTransit).toBe(r.openOrders.reduce((a,o)=>a+o.quantity,0));expect(r.metrics.orderedQuantity).toBe(r.steps.reduce((a,s)=>a+s.receipts,0)+r.metrics.inTransit);});
  it('мутация контекста плагином не влияет на историю и политику',()=>{const input=fixture(),before=structuredClone(input);simulate(input,c=>{const d=naiveStrategy(c);c.settings.packSize=999;c.history[0]!.demand=999;return d;},'mutable');expect(input).toEqual(before);});
  it('адаптер сортирует только выбранный SKU и валидирует',()=>{const input=fixture();const rows=input.observations.map(o=>({sku:o.sku,weekStart:o.date,salesUnits:o.demand})).reverse();expect(fromStockPilot(rows,input).observations).toEqual(input.observations);});
});
