'use client';

import { useEffect, useState } from 'react';
import { CartesianGrid, Legend, Line, LineChart, ReferenceDot, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { createDemo } from '../data/demo/generate';
import { BacktestInputSchema, type BacktestInput, type BacktestResult, type BacktestMetrics } from './contracts';
import { compareStrategies, type StrategyPair } from './engine';
import { exportCsv } from './csv';
import styles from './BacktestPanel.module.css';
export interface BacktestPanelProps {
  initialInput?:BacktestInput;
  inputs?:readonly BacktestInput[];
  strategies?:StrategyPair;
  strategyNotice?:string;
  allowDemo?:boolean;
  onResults?:(results:readonly BacktestResult[])=>void;
}
const defaults:BacktestInput['settings']={initialStock:45,leadTimeDays:21,reviewPeriod:1,moq:5,packSize:5,serviceLevel:'0.95'};
const format=(v:number)=>v.toLocaleString('ru-RU',{maximumFractionDigits:1});
export function BacktestPanel({initialInput,inputs,strategies,strategyNotice,allowDemo=true,onResults}:BacktestPanelProps) {
  const [catalog,setCatalog]=useState<ReturnType<typeof createDemo>>([]);
  const [input,setInput]=useState<BacktestInput|undefined>(initialInput??inputs?.[0]);
  const [results,setResults]=useState<readonly BacktestResult[]>();
  const [error,setError]=useState(''); const [cursor,setCursor]=useState(0); const [playing,setPlaying]=useState(false);
  useEffect(()=>{if(!playing||!results)return;const id=window.setTimeout(()=>{if(cursor>=results[0]!.steps.length-1)setPlaying(false);else setCursor(cursor+1);},850);return()=>window.clearTimeout(id);},[playing,results,cursor]);
  function select(item:ReturnType<typeof createDemo>[number]) { setInput({sku:item.sku,observations:item.observations,startIndex:item.kind==='short'?2:20,endIndex:item.observations.length-1,settings:{...defaults,leadTimeDays:item.leadTimeDays,packSize:item.packSize},unitCost:item.unitCost,currency:'₸',source:'sales'});setResults(undefined);setPlaying(false);setError(''); }
  function change(next:BacktestInput) {setInput(next);setResults(undefined);setPlaying(false);setError('');}
  function run(){const parsed=BacktestInputSchema.safeParse(input);if(!parsed.success){setError(parsed.error.issues.map(i=>i.message).join('; '));return;}try{const r=compareStrategies(parsed.data,strategies);setResults(r);setCursor(r[0].steps.length-1);setPlaying(false);setError('');onResults?.(r);}catch(e){setError(e instanceof Error?e.message:'Ошибка расчёта');}}
  function download(){if(!results)return;const url=URL.createObjectURL(new Blob([exportCsv(results)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`stockpilot-${input?.sku}.csv`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const a=results?.[0],b=results?.[1];
  const chart=a?.steps.slice(0,cursor+1).map((s,i)=>({date:s.date,naive:s.endingStock,robust:b!.steps[i]!.endingStock}));
  const metrics:[keyof BacktestMetrics,string][]=[['servedDemand','Обслуженный спрос, ед.'],['unmetDemand','Потерянный спрос, ед.'],['fillRate','Доля удовлетворённого спроса'],['shortagePeriods','Недель с дефицитом'],['averageEndingStock','Средний конечный запас, ед.'],['maxStock','Максимальный запас до спроса, ед.'],['orderCount','Количество заказов'],['orderedQuantity','Заказано, ед.'],['purchaseCost','Стоимость закупок'],['averageInventoryCost','Стоимость среднего запаса'],['endingStock','Остаток на конец, ед.'],['inTransit','Поставки в пути на конец, ед.']];
  return <section className={styles.panel}>
    <header className={styles.header}><div><div className={styles.eyebrow}>STOCKPILOT AI / ЛАБОРАТОРИЯ ЗАКУПОК</div><h1>Проверка на прошлом</h1><p>Одна история. Одинаковые условия. Две стратегии закупок.</p></div>{allowDemo&&<button type="button" className={styles.secondary} onClick={()=>{const demo=createDemo();setCatalog(demo);select(demo[0]!);}}>Загрузить демо</button>}</header>
    <div className={styles.notice}>{strategies?(strategyNotice??"Подключена внешняя стратегия StockPilot. Правила пополнения одинаковы для обеих стратегий."):"Демонстрационная устойчивая стратегия. Подключение основного движка StockPilot ещё не выполнено."}</div>
    {!input?<div className={styles.empty}><h2>Проверьте решения на истории</h2><p>Загрузите 6 воспроизводимых сценариев: от стабильного спроса до разового всплеска.</p><p>Все расчёты выполняются локально. Данные никуда не отправляются.</p></div>:<>
      <div className={styles.card}><div className={styles.sectionTitle}><h2>01 / Условия эксперимента</h2><span>Недельная детализация</span></div><div className={styles.fields}>
        <label className={styles.wide}>Товар / SKU<select value={input.sku} onChange={e=>{const item=catalog.find(x=>x.sku===e.target.value);if(item)select(item);else {const external=inputs?.find(x=>x.sku===e.target.value);if(external)change(external);}}}>{catalog.length?catalog.map(x=><option key={x.sku} value={x.sku}>{x.sku} — {x.label}</option>):inputs?.length?inputs.map(x=><option key={x.sku} value={x.sku}>{x.sku}</option>):<option>{input.sku}</option>}</select></label>
        <label>Начало проверки<select value={input.startIndex} onChange={e=>change({...input,startIndex:Number(e.target.value)})}>{input.observations.map((o,i)=><option key={o.date} value={i}>{o.date}</option>)}</select></label>
        <label>Конец проверки<select value={input.endIndex} onChange={e=>change({...input,endIndex:Number(e.target.value)})}>{input.observations.map((o,i)=><option key={o.date} value={i}>{o.date}</option>)}</select></label>
        {([['initialStock','Начальный запас, ед.'],['leadTimeDays','Срок поставки, дней'],['reviewPeriod','Пересмотр, недель'],['moq','MOQ, ед.'],['packSize','Упаковка, ед.']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min={key==='packSize'||key==='reviewPeriod'?1:0} step="1" value={Number.isNaN(input.settings[key])?'':input.settings[key]} onChange={e=>change({...input,settings:{...input.settings,[key]:e.target.value===''?NaN:Number(e.target.value)}})}/></label>)}
        <label>Уровень сервиса<select value={input.settings.serviceLevel} onChange={e=>change({...input,settings:{...input.settings,serviceLevel:e.target.value as BacktestInput['settings']['serviceLevel']}})}>{['0.5','0.9','0.95','0.99'].map(v=><option key={v} value={v}>{Number(v)*100}%</option>)}</select></label>
      </div><div className={styles.runbar}><p>Разогрев: {input.startIndex} недель · Поставка: {Math.ceil(input.settings.leadTimeDays/7)} недель · Начальный запас задан вручную</p><button type="button" onClick={run}>Запустить сравнение</button></div>{error&&<p role="alert" className={styles.error}>{error}</p>}</div>
      {a&&b&&<><div className={styles.kpis}>{[a,b].map(r=><div className={styles.card} key={r.strategy}><div className={styles.eyebrow}>{r.strategy}</div><strong>{format(r.metrics.fillRate*100)}<small>% спроса обслужено</small></strong><p><span className={styles.error}>{format(r.metrics.unmetDemand)} ед. потеряно</span> · {format(r.metrics.averageEndingStock)} ед. среднего запаса</p></div>)}</div>
      <div className={styles.card}><div className={styles.sectionTitle}><h2>02 / История запасов</h2><button type="button" className={styles.secondary} onClick={download}>Экспорт CSV</button></div><div className={styles.chart}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart} margin={{left:0,right:20,top:16,bottom:4}}><CartesianGrid strokeDasharray="3 3" stroke="#e4e9eb"/><XAxis dataKey="date" tick={{fontSize:11}} tickFormatter={v=>String(v).slice(5)}/><YAxis/><Tooltip/><Legend/><Line name={a.strategy} dataKey="naive" stroke="#64748b" dot={false} strokeWidth={2} isAnimationActive={false}/><Line name={b.strategy} dataKey="robust" stroke="#008f86" dot={false} strokeWidth={3} isAnimationActive={false}/>{a.steps.slice(0,cursor+1).filter((s,i)=>s.unmet>0||b.steps[i]!.unmet>0).map(s=><ReferenceLine key={s.date} x={s.date} stroke="#d23e42" strokeDasharray="3 3"/>)}{[a,b].flatMap((r,k)=>r.steps.slice(0,cursor+1).flatMap(s=>[...(s.ordered>0?[<ReferenceDot key={`${k}-${s.date}-order`} x={s.date} y={s.endingStock} r={5} fill="white" stroke="#d59929" strokeWidth={2}/>]:[]),...(s.receipts>0?[<ReferenceDot key={`${k}-${s.date}-receipt`} x={s.date} y={s.endingStock} r={2} fill="#008f86" stroke="#008f86"/>]:[])]))}</LineChart></ResponsiveContainer></div>
      <p className={styles.hint}>Линии — конечный запас. Красные пунктиры — недели с дефицитом хотя бы у одной стратегии. Янтарные кольца — заказы, бирюзовые точки — поступления. Подробности — в журнале ниже.</p>
      <div className={styles.playback}><button type="button" className={styles.secondary} onClick={()=>{setCursor(0);setPlaying(false);}}>В начало</button><button type="button" onClick={()=>{if(cursor===a.steps.length-1)setCursor(0);setPlaying(!playing);}}>{playing?'Пауза':'Проиграть'}</button><button type="button" className={styles.secondary} disabled={cursor>=a.steps.length-1} onClick={()=>{setPlaying(false);setCursor(c=>Math.min(c+1,a.steps.length-1));}}>Шаг →</button><input aria-label="Неделя проигрывания" type="range" min="0" max={a.steps.length-1} value={cursor} onChange={e=>{setPlaying(false);setCursor(Number(e.target.value));}}/><b>{a.steps[cursor]?.date}</b></div>
      <div className={styles.events}>{[a,b].map(r=>{const s=r.steps[cursor]!;return <div key={r.strategy}><h3>{r.strategy}</h3><p>Спрос: <b>{s.demand}</b> · Отгрузка: <b>{format(s.served)}</b></p><span className={styles.badge}>↑ Заказ {s.ordered}</span> <span className={styles.badge}>↓ Приход {s.receipts}</span> <span className={s.unmet?styles.shortage:styles.badge}>Дефицит {format(s.unmet)}</span><p>Остаток {format(s.endingStock)} · В пути {s.inTransit}</p><p className={styles.hint}>{s.decision?`Прогноз ${format(s.decision.forecast)} ед./нед. · скорректировано наблюдений: ${s.decision.adjustedCount}`:'Неделя без пересмотра'}</p></div>;})}</div></div>
      <div className={styles.card}><h2>03 / Итог за весь выбранный период</h2><div className={styles.tableWrap}><table><thead><tr><th>Показатель</th><th>{a.strategy}</th><th>{b.strategy}</th></tr></thead><tbody>{metrics.map(([key,label])=><tr key={key}><td>{label}</td>{[a,b].map(r=><td key={r.strategy}>{r.metrics[key]===undefined?'Нет себестоимости':key==='fillRate'?`${format(r.metrics[key]*100)}%`:`${format(r.metrics[key])}${key==='purchaseCost'||key==='averageInventoryCost'?` ${r.currency}`:''}`}</td>)}</tr>)}</tbody></table></div><p className={styles.hint}>Стоимость закупок учитывает размещённые заказы, включая товар в пути. Разница не является прибылью или гарантированной экономией.</p></div>
      <details className={styles.card}><summary>Полный журнал событий</summary><div className={styles.tableWrap}><table><thead><tr><th>Неделя / стратегия</th><th>Заказ ↑</th><th>Приход ↓</th><th>Дефицит</th><th>Остаток</th></tr></thead><tbody>{a.steps.flatMap((_,i)=>[a,b].map(r=>{const s=r.steps[i]!;return <tr key={`${r.strategy}-${i}`}><td>{s.date} / {r.strategy}</td><td>{s.ordered||'—'}</td><td>{s.receipts||'—'}</td><td className={s.unmet?styles.error:''}>{format(s.unmet)}</td><td>{format(s.endingStock)}</td></tr>;}))}</tbody></table></div></details></>}
    </>}
    <details className={styles.assumptions} open><summary>Допущения и ограничения</summary><ul><li>{input?.source==="demand"?"Используется предоставленная история спроса.":"Продажи используются как приближение спроса. Скрытый спрос во время исторического дефицита неизвестен."}</li><li>Неудовлетворённый спрос теряется, задолженность не переносится. Обе стратегии стартуют с одинаковым заданным запасом и без открытых заказов.</li><li>Порядок недели: поступления → прогноз по прошлым неделям → заказ → спрос → остаток. При нулевом сроке новый заказ приходит до спроса этой недели.</li><li>Срок поставки округляется вверх до недель. Измеряются недели с дефицитом, точное число дней неизвестно.</li><li>Уровень сервиса задаёт коэффициент страхового запаса, а не гарантирует фактическую долю обслуживания. Рост и сезонность не моделируются; устойчивая стратегия может проиграть.</li><li>Исходные наблюдения сохранены. Не учитываются ограничения бюджета, хранение, возвраты, скидки и неопределённость поставок.</li></ul></details>
  </section>;
}


